export const CUSTOMER_REGISTER = 'CUSTOMER_REGISTER';
export const CUSTOMER_LOGIN = 'CUSTOMER_LOGIN';
export const CUSTOMER_LOGOUT = 'CUSTOMER_LOGOUT';
export const CUSTOMER_AUTH = 'CUSTOMER_AUTH';
export const CUSTOMER_CHANGE_PASSWORD = 'CUSTOMER_CHANGE_PASSWORD';
export const CUSTOMER_FORGOTPASSWORD = 'CUSTOMER_FORGOTPASSWORD';
export const CUSTOMER_RESETPASSWORD = 'CUSTOMER_RESETPASSWORD';